### ISSUE TITLE
Provide example usage

### ISSUE THREAD

**Issue by Steve973** [audit4j/audit4j-microservice#1]
As a potential user of the microservice, I need to know how to use it.

Please provide tests and javadoc, etc, to give a potential user of this microservice a good idea about how it should be used.  It would be a good idea to open it for code review, as well, to get some opinions about how these things are implemented.

**Comment by isaaclong1** [comment]
@janithb I know it has been a long time, but is there any update on this? I downloaded this today and can't run it without a "server.config.yaml" file (or maybe this is a standard file that I am unaware of, either way there is very little instruction on how to get this running and test it). We are interested in using this or forking it for a project that needs an auditor in a microservice environment. Your help would be much appreciated! Thanks

**Comment by janithb** [comment]
@isaaclong @Steve973 

Please follow the instruction on updated README. :)

**Comment by janithb** [comment]
Please refer [SmokeTest](https://github.com/audit4j/audit4j-microservice/blob/master/src/test/java/org/audit4j/microservice/SmokeTest.java) class to send audit events to the server. Custom client handler should be implemented.

**Comment by Steve973** [comment]
Thanks for the update on usage.  However, there are some details that concern me a bit.  I definitely appreciate your work, and I mean these things in the spirit of ease of adoption, ease of use, to most easily encourage contributions, and from a quality standpoint.  I do not mean any of my comments to be insulting or condescending, so please ask me for clarification if any of my points seem to be out of line.

**Regarding the code base itself**
1. There is almost no javadoc.  If this should be a community project, and if you would like community participation (e.g., contributions) it would be very helpful to know what a method should expect as input, and what it produces.  It is also very important to know what the method is _**intended to do**_.  I contribute most readily when things are easy to follow.
2. There are no actual tests.  The ["SmokeTest" class](https://github.com/audit4j/audit4j-microservice/blob/master/src/test/java/org/audit4j/microservice/SmokeTest.java) is an example (or a demo), but it is not a test that is invoked from the build, and it does not contain stimulus and response that is verified.  As such, any modifications or contributions could render it broken without verification at build time.  Moreover, from the perspective of sharing this as a github community project, the lack of unit and integration tests means that unintended consequences of contributions/modifications won't be verified against the currently implemented features.
3. Generated code is committed to the source tree.  Consider generating code to a folder in the target directory for inclusion in the built archive.  Generated resources, strictly speaking, are not really source, even if they are processed/built and included in the deliverable.

If you could address some of these things, I would be happy to help out with the project and also do a complete code review if that would help.

**Regarding features and how to use them**
1. Since your readme is likely the first thing that a prospective user will see, it would be good to let them know why they should use this microservice.  There is a reason why you wrote it -- a problem that you wanted to solve, or a use case that something else would not solve for you.  If you highlight these ideas, it could encourage more people to use it to solve their problems.  The question that is most obvious to me is: "As a Java developer, what are the benefits of using this microservice over using audit4j directly?"
2. It might be helpful to mention features of Audit4J itself, and how to utilize them in your microservice.  a feature-by-feature comparison would be extremely helpful.  If people already know audit4j, then this would decrease their learning curve to a very minimal level.
3. Audit4J alleviates the need to clutter your codebase with the orthogonal concern of auditing by providing annotations.  If we use the microservice, it would be nice to provide an example of how to avoid mixing auditing with business logic.  That doesn't appear to be the focus of this project, but mentioning a few methods in various languages would be helpful to at least some developers.
4. Is it possible to have multiple audit record destinations?  For example, if I want a security audit record datastore and a customer order audit record datastore, is it possible to use both of these with one instance of the microservice?  If not, that might be a cool feature: configure multiple audit record datastores and provide a way to designate which store should receive various events.

Thanks again, and feel free to reach out to me for anything.

**Comment by janithb** [comment]
@Steve973 

I really appreciate your feedback and lengthy but valuable ideas.  I understand what you are saying and I know this project is lacking docs and test classes that's why the project is not yet released. I have open an another [issue ](#3) to address this. 

If you mean [thrift generated stubs](https://github.com/audit4j/audit4j-microservice/tree/master/src/main/java/org/audit4j/microservice/transport/thrift) , I don't think there is an issue with keeping the generated stubs the source tree, I'm pretty sure If you use SOAP, you'll do the same.

Honestly these days I'm in a busy schedule with my current employer. I'll try to improve the project when I have free time. I'll make a note about your other ideas. 

I would be grateful if you could participate and do some contributions. Thanks for the help anyway.
