### ISSUE TITLE
Provide a script to run on Linux

### ISSUE THREAD

**Issue by Steve973** [audit4j/audit4j-microservice#2]
It appears that only a windows batch file is provided.  Please provide a way to run this on Linux.

**Comment by janithb** [comment]
Currently I'm not working in the Windows PC, appreciate if you have can you write a shell script similar to the batch file. we do accept pull requests.

**Comment by allouzi** [comment]
you can use it as below

#!/bin/bash
java -cp "lib/*"  org.audit4j.microservice.Main
